[phases.setup]
nixPkgs = ['php81', 'php81Packages.composer', 'nodejs-18_x', 'npm']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci --only=production'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'

[variables]
PHP_EXTENSIONS = 'gd,zip,bcmath,ctype,fileinfo,json,mbstring,openssl,pdo,tokenizer,xml'